---
# Playbook для обновления периферийных информационных баз

- name: Update 1C Enterprise
  hosts: store

# Переменные доступные плэйбуку
  vars:
    v8version: 8.3.9.2309
    server_agent_srv_name: '1C:Enterprise 8.3 Server Agent'
    DataBaseName: "localhost/Retail"
    DataBase: /S{{ DataBaseName }}
    AdminUser: /N"Intellect" /p "Intel+756" /WA-
    v8exe: C:\Program Files (x86)\1cv8\{{ v8version }}\bin\1cv8.exe
    srv_1c_pwd: "Intel+756"

  tasks:
    # Пингуемся перед запуском первой задачи
    - name: Test connection
      win_ping:

    - name: Kill 1cv8s.exe command
      win_command: cmd.exe /c TASKKILL /F /IM "1cv8s.exe"

    - name: Kill 1cv8c.exe command
      win_command: cmd.exe /c TASKKILL /F /IM "1cv8s.exe"

    - name: Kill 1cv8.exe command
      win_command: cmd.exe /c TASKKILL /F /IM "1cv8s.exe"

    - name: Kill terminated RBD_Exchange.exe command
      win_command: cmd.exe /c TASKKILL /F /IM "RBDExchange.exe"

    # Остановка службы сервера 1С
    - name: Stop server agent service
      win_service:
        name: '{{ server_agent_srv_name }}'
        state: stopped
      when: server_agent_srv_info.exists

    # Запуск службы сервера 1С
    - name: Start server agent service
      win_service:
        name: '{{ server_agent_srv_name }}'
        state: started
      when: server_agent_srv_info.exists

    # Запускаем на обновление RBD Exchange
    - name: Start RBD Exchange service
      win_command: cmd.exe "C:\RBDExchange\RBDExchange.exe" /b /e

    # Обновление конфигурации базы данных
    - name: Configuration 1C Update
      win_command: cmd.exe start "" /wait '{{v8exe}}' CONFIG '{{DataBase}}' '{{AdminUser}}' /UpdateDBCfg /UCКодРазрешения

    # Запускаем на обновление RBD Exchange
    - name: Start RBD Exchange finall
      win_command: cmd.exe "C:\RBDExchange\RBDExchange.exe" /b /e
