---
# Playbook для обновления периферийных информационных баз
# Данный скрипт проводит только запускает обновление, без обновления конфигурации

- name: Update 1C Enterprise
  hosts: store_servers_2012

# Переменные доступные плэйбуку
  vars:
    v8version: 8.3.9.2309
    server_agent_srv_name: '1C:Enterprise 8.3 Server Agent'
    DataBaseName: "localhost/Retail"
    DataBase: /S"localhost/Retail"
    AdminUser: /N"Intellect" /p "Intel+756" /WA-
    v8dir: C:\Program Files (x86)\1cv8\8.3.9.2309\bin\
    v8exe: C:\Program Files (x86)\1cv8\8.3.9.2309\bin\1cv8.exe
    srv_1c_pwd: "Intel+756"

  tasks:
    # Пингуемся перед запуском первой задачи
    - name: Test connection
      win_ping:

    - name: Kill RBDExchange.exe command
      #ignore_errors: yes
      win_command: cmd.exe /c tasklist | find /i "RBDExchange.exe" && taskkill /IM RBDExchange.exe /T /F || echo process "RBDExchange.exe" not running.

    # Запускаем на обновление RBD Exchange
    - name: Start RBD Exchange service
      win_command: cmd.exe /C CD C:\RBDExchange && RBDExchange.exe /b /e
