---
# Playbook для обновления периферийных информационных баз
- name: Update 1C Enterprise
  hosts: store_servers

# Переменные доступные плэйбуку
#  vars:
#    v8version: 8.3.9.2309
#    server_agent_srv_name: '1C:Enterprise 8.3 Server Agent'
#    DataBaseName: "localhost/Retail"
#    DataBase: /S{{ DataBaseName }}
#    AdminUser: /N"Intellect" /p "Intel+756" /WA-
#    v8exe: C:\Program Files (x86)\1cv8\{{ v8version }}\bin\1cv8.exe
#    srv_1c_pwd: "Intel+756"
  tasks:

    # Пингуемся перед запуском первой задачи
    - name: Test connection
      win_ping:
